@FidelityCard.Srv_HostAddress = http://localhost:5121

### Esempio di richiesta GET
GET {{FidelityCard.Srv_HostAddress}}/api/examples
Accept: application/json
###

### Esempio di richiesta POST con parametro json
### POST {{FidelityCard.Srv_HostAddress}}/api/esamples
### Content-Type: application/json
### Accept: application/json
### 
### {
###   "name": "Mario Rossi",
###   "email": "mario.rossi@example.com",
###   "age": 30
### }
###